# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-30 01:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_auto_20181030_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terminaluser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='terminaluser',
            name='service',
        ),
        migrations.RemoveField(
            model_name='terminaluser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='TerminalUser',
        ),
    ]
