# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-30 01:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_app', '0004_serviceuser'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='serviceuser',
            unique_together=set([('service', 'user')]),
        ),
    ]
