# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-30 01:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0005_auto_20181030_0121'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTerminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.Service')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.Terminal')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='serviceterminal',
            unique_together=set([('service', 'terminal')]),
        ),
    ]
