# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-30 03:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_app', '0010_auto_20181030_0322'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveIntegerField()),
                ('date_join', models.DateTimeField(auto_now=True)),
                ('date_call', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.Service')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.Terminal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveIntegerField()),
                ('date_join', models.DateTimeField(auto_now=True)),
                ('date_call', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.Service')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.Terminal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
