# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-30 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0011_quelog_queue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quelog',
            name='date_call',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quelog',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='queue',
            name='date_call',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='queue',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
