# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-31 01:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0014_auto_20181031_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminal',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core_app.Service'),
        ),
    ]
