# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-31 01:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_app', '0016_terminaluser'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='terminaluser',
            unique_together=set([('terminal', 'user')]),
        ),
    ]
