# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-31 01:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0019_auto_20181031_0141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='date_call',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='terminal',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='user',
        ),
    ]
